
# Documentation: https://github.com/codecov/support/wiki/codecov.yml
# Validate with: curl --data-binary @.codecov.yml https://codecov.io/validate

codecov:
  notify:
    require_ci_to_pass: no

comment: false
