language: go

go:
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - tip

env:
- GO111MODULE=on

notifications:
  email: false

install: true

script:
- make test

after_success:
- bash <(curl -s https://codecov.io/bash)
